name: Pantheon Deploy

on:
  push:
    branches:
      - main  # Replace with your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Set Node.js version 14.x

      - name: Install dependencies
        run: |
          npm install axios # Install any necessary packages for your script
          
      - name: Run Node.js deploy script
        run: |
          node scripts/deploy.js # Make sure the path matches the location of your script

      - name: Output successful deployment
        run: echo "Deployment to Pantheon was successful!"
